### ISSUE TITLE
Can't get value from powermeter

### ISSUE THREAD

**Issue by arthur-esob** [clade/ThorlabsPM100#4]
Bonjour Pierre,
I'm trying to get power values from a PM100.
here is the very simple code to test i'm using:

from __future__ import print_function

from time import sleep
from numpy import array
import visa

from ThorlabsPM100 import ThorlabsPM100
import ctypes

rm = visa.ResourceManager()
inst = rm.open_resource('USB0::0x1313::0x8072::P2004152::INSTR',timeout=1)

power_meter = ThorlabsPM100(inst=inst)
power_meter = ThorlabsPM100(inst = inst)

power_meter.system.beeper.immediate()
power_meter.read()

returns : <ThorlabsPM100.ThorlabsPM100.read object at 0x02190FD0>
Seems like the value is stored at the address : 0x02190FD0 but i can't get to read the value stored at this address.
Seems like i'm not using your script properly.
Do you have any idea ?
Thanks for your help.

Pierre, from Bordeaux

**Comment by arthur-esob** [comment]
executing the example.py gives the following result:

Measurement type : <class 'ThorlabsPM100.ThorlabsPM100.getconfigure'>
Current value    : <class 'ThorlabsPM100.ThorlabsPM100.read'>
Wavelength       : <class 'ThorlabsPM100.SenseCorrection.wavelength'>
Power range limit: <class 'ThorlabsPM100.SensePowerDcRange.upper'>
Set range auto and wait 500ms    ...
Power range limit: <class 'ThorlabsPM100.SensePowerDcRange.upper'>
Set bandwidth to High
Average per mesure : <class 'ThorlabsPM100.SenseAverage.count'>
Set average to 1 ...
Perform 100 measurements ...
Traceback (most recent call last):
  File "C:/Python34/Scripts/ThorlabsPM100-1.1.2/ThorlabsPM100/reference.py", line 39, in <module>
    print("Average value      :", mes.mean())
  File "C:\Python34\lib\site-packages\numpy\core\_methods.py", line 70, in _mean
    ret = umr_sum(arr, axis, dtype, out, keepdims)
TypeError: unsupported operand type(s) for +: 'type' and 'type'

**Comment by clade** [comment]
ThorlabsPM100 is written for Python 2. In order to use it with Python 3 you should run the 2to3 script. This is done automatically if you install the package ( via pip or python setup.py install).

**Comment by arthur-esob** [comment]
Bonjour Pierre

j'ai effectivement lancé le setup.py et le problème est toujours le même 😞.

je vais essayer deux choses:

- lancer le script avec python 2.7 pour voir si j'ai plus de chance.

- lancer manuellement le script 2to3 car je compte utiliser ton script pour interfacer d'autres instruments requérant python3.

bon week end

Pierre


________________________________
De : Pierre Cladé <notifications@github.com>
Envoyé : vendredi 26 janvier 2018 17:56
À : clade/ThorlabsPM100
Cc : arthur-esob; Author
Objet : Re: [clade/ThorlabsPM100] Can't get value from powermeter (#4)


ThorlabsPM100 is written for Python 2. In order to use it with Python 3 you should run the 2to3 script. This is done automatically if you install the package ( via pip or python setup.py install).

**Comment by clade** [comment]
I'm pretty sure that you should not see the same behavior after installation of the package. 
Are you in the same directory as before (you should change if you don't want to import the local) ?
Are the installed files (especially the file ThorlabsPM100.py) modified ? You can see where they are installed looking to the variable ThorlabsPM100.__file__

**Comment by clade** [comment]
I have uploaded in the dev branch a version that should work with both python 2 and python 3 directly. Not test yet.

**Comment by j-venture** [comment]
Hello, Thank you for uploading this project.
I installed this on Python 3.4.1 but sill see the same outputs as this user does , also I still seem to have to call ThorlabsPM100.ThorlabPM100(inst) instead of ThorlabsPM100.(inst).

Finally my device appears at USBTMC1 not USBTMC0, should that be an issue?

**Comment by clade** [comment]
How did you install the package ? Which version are you using. 
Please use the version in the dev branch (https://github.com/clade/ThorlabsPM100/archive/dev.zip)

The USBTMC1 instead of USBTMC0 is not an issue
Looking to the program, I agree that you should call `ThorlabsPM100.ThorlabPM100(inst)`. I will patch this.

**Comment by j-venture** [comment]
It is working now, I had implemented the install incorrectly (embarrassing on my part).  I am still able to use Thorlabs.Thorlabs and will use the dev branch.  Thanks for the quick response!!
